#pragma once

enum PacketType : uint8_t {
	PACKET_HEALTH,
	PACKET_CURRENTLY_PLAYING,
	PACKET_FILE_EXISTS,
	PACKET_FILE_OPEN,
	PACKET_FILE_START_WRITE,
	PACKET_FILE_CONTINUE_WRITE,
	PACKET_FILE_DISPLAY
};

enum HealthStatus : uint8_t {
	HEALTH_OK,
	HEALTH_DISPLAY_ERROR,
	HEALTH_SD_ERROR,
	HEALTH_UNK_ERROR,

	HEALTH_ASKED
};

enum PacketDirection : uint8_t {
	DIRECTION_ESP_TO_DEVICE = 'E',
	DIRECTION_DEVICE_TO_ESP = 'D'
};